Remove unused paramter error
ethz-adrl/ifopt pull request #98
Opened 2023-08-28 21:01 UTC by Kotochleb

While compiling, constrain set was returning error on unused parameter.

I was considering adding `[[maybe_unused]]` to suppress the error (that would force C++17), or to use `__attribute__((__unused__))` (that would break windows compatibility). Anyway, I decided to use this approach. Hope you find this solution acceptable.

2023-08-29 14:49 UTC, Levi-Armstrong requested changes

2023-08-29 14:49 UTC, Levi-Armstrong commented on ifopt_core/include/ifopt/constraint_set.h
> -  virtual void InitVariableDependedQuantities(const VariablesPtr& x_init){};
Replace `x_init` with `/*x_init*/` and that will solve the issue so no need to add `(void) x_init`.

2023-08-29 14:49 UTC, Levi-Armstrong commented on ifopt_core/include/ifopt/constraint_set.h
> -  void SetVariables(const VectorXd& x) final { assert(false); };
Replace `x` with `/*x*/` and that will solve the issue so no need to add `(void) x`.

2023-08-29 20:38 UTC, Kotochleb commented
I changed to commenting it out. I have absolutely no idea why it didn't cross my mind. Sorry for bothering with review on such small change

2023-08-31 19:28 UTC, Levi-Armstrong approved these changes

2023-08-31 19:28 UTC, merged